# Generated by Django 5.2.12 on 2026-04-12 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_courseprogress_favoritecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles')),
                ('approved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contentinteraction',
            name='article',
        ),
        migrations.RemoveField(
            model_name='contentinteraction',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contentinteraction',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='contentinteraction',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='time_spent',
        ),
        migrations.RemoveField(
            model_name='favoritecontent',
            name='article',
        ),
        migrations.RemoveField(
            model_name='favoritecontent',
            name='course',
        ),
        migrations.AddField(
            model_name='contentinteraction',
            name='content_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contentinteraction',
            name='interaction_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='course_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favoritecontent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favoritecontent',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
